### ISSUE TITLE
Create wireframe for selecting and connecting Autocomplete connectors to a field

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho-req#257]
Each field can have their own autocomplete.  The options for the autocomplete will come from one of the connectors defined in #254, #255, & #256. Additionally, there will be the option for a user-defined list of values at a later time.

The linked tickets above block this work because we need to know the details of what's required for each connector in order to write the UI to choose it.

**Comment by awead** [comment]
Use in creating a template. When a field is added to the template, an autocomplete source will be attached to that field.

**Comment by awead** [comment]
Since the autocompletes will be simple drop-down menus, this work will be accomplished during template creation.
