### ISSUE TITLE
geo coordinates search

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/cho-req#32]
As a user,
I would like to be able to search objects by location,
So that I may contextualize my search results by coordinates/location.

**Comment by ntallman** [comment]
@DanCoughlin Did you mean enter a query like (Dubois, PA) or did you mean an interactive map with the content plotted and drill-down map searching?

**Comment by ntallman** [comment]
Duplicate of #109, which is more articulated. Closing this version.
